name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci-test-deploy:
    permissions:
      contents: read
      deployments: write
    env:
      BUILD_DIRECTORY: out
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Bun version
        run: bun --version
      - name: Node version
        run: node --version
      - name: Install Bun dependencies
        run: bun install --frozen-lockfile
      - name: Test (types)
        run: bun run test:types
      - name: Test (units)
        run: bun run test:units
      - name: Test (lint)
        run: bun run test:lint
      - name: Test (formatting)
        run: bun run test:format
      - name: Build
        run: bun run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: audio-playground
          directory: ./${{env.BUILD_DIRECTORY}}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload static output artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./${{env.BUILD_DIRECTORY}}
  ci-render:
    needs: [ci-test-deploy]
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
      - name: Bun version
        run: bun --version
      - name: Node version
        run: node --version
      - name: Install Bun dependencies
        run: bun install --frozen-lockfile
      - name: Playwright version
        run: bunx playwright --version
      - name: Install Playwright browsers
        run: bunx playwright install --with-deps
      - name: Build
        run: bun run build
      - name: Render audio
        run: bun run render:audio
      - name: Upload renders artifacts
        uses: actions/upload-artifact@v4
        with:
          name: renders
          path: ./playwright-artifacts
